/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
	onecloudv1alpha1 "yunion.io/x/onecloud-operator/pkg/apis/onecloud/v1alpha1"
	versioned "yunion.io/x/onecloud-operator/pkg/client/clientset/versioned"
	internalinterfaces "yunion.io/x/onecloud-operator/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "yunion.io/x/onecloud-operator/pkg/client/listers/onecloud/v1alpha1"
)

// OnecloudClusterInformer provides access to a shared informer and lister for
// OnecloudClusters.
type OnecloudClusterInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.OnecloudClusterLister
}

type onecloudClusterInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewOnecloudClusterInformer constructs a new informer for OnecloudCluster type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewOnecloudClusterInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredOnecloudClusterInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredOnecloudClusterInformer constructs a new informer for OnecloudCluster type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredOnecloudClusterInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.OnecloudV1alpha1().OnecloudClusters(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.OnecloudV1alpha1().OnecloudClusters(namespace).Watch(context.TODO(), options)
			},
		},
		&onecloudv1alpha1.OnecloudCluster{},
		resyncPeriod,
		indexers,
	)
}

func (f *onecloudClusterInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredOnecloudClusterInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *onecloudClusterInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&onecloudv1alpha1.OnecloudCluster{}, f.defaultInformer)
}

func (f *onecloudClusterInformer) Lister() v1alpha1.OnecloudClusterLister {
	return v1alpha1.NewOnecloudClusterLister(f.Informer().GetIndexer())
}
