//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	appsv1 "k8s.io/api/apps/v1"
	v1 "k8s.io/api/core/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIGatewaySpec) DeepCopyInto(out *APIGatewaySpec) {
	*out = *in
	in.DeploymentSpec.DeepCopyInto(&out.DeploymentSpec)
	out.APIService = in.APIService
	out.WSService = in.WSService
	if in.CorsHosts != nil {
		in, out := &in.CorsHosts, &out.CorsHosts
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIGatewaySpec.
func (in *APIGatewaySpec) DeepCopy() *APIGatewaySpec {
	if in == nil {
		return nil
	}
	out := new(APIGatewaySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BaremetalAgentStatus) DeepCopyInto(out *BaremetalAgentStatus) {
	*out = *in
	in.DeploymentStatus.DeepCopyInto(&out.DeploymentStatus)
	if in.ZoneBaremetalAgent != nil {
		in, out := &in.ZoneBaremetalAgent, &out.ZoneBaremetalAgent
		*out = make(map[string]*DeploymentStatus, len(*in))
		for key, val := range *in {
			var outVal *DeploymentStatus
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = new(DeploymentStatus)
				(*in).DeepCopyInto(*out)
			}
			(*out)[key] = outVal
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BaremetalAgentStatus.
func (in *BaremetalAgentStatus) DeepCopy() *BaremetalAgentStatus {
	if in == nil {
		return nil
	}
	out := new(BaremetalAgentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BaremetalConfig) DeepCopyInto(out *BaremetalConfig) {
	*out = *in
	out.ServiceCommonOptions = in.ServiceCommonOptions
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BaremetalConfig.
func (in *BaremetalConfig) DeepCopy() *BaremetalConfig {
	if in == nil {
		return nil
	}
	out := new(BaremetalConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Clickhouse) DeepCopyInto(out *Clickhouse) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Clickhouse.
func (in *Clickhouse) DeepCopy() *Clickhouse {
	if in == nil {
		return nil
	}
	out := new(Clickhouse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudUser) DeepCopyInto(out *CloudUser) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudUser.
func (in *CloudUser) DeepCopy() *CloudUser {
	if in == nil {
		return nil
	}
	out := new(CloudUser)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudmonSpec) DeepCopyInto(out *CloudmonSpec) {
	*out = *in
	in.DeploymentSpec.DeepCopyInto(&out.DeploymentSpec)
	out.Service = in.Service
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudmonSpec.
func (in *CloudmonSpec) DeepCopy() *CloudmonSpec {
	if in == nil {
		return nil
	}
	out := new(CloudmonSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudmuxSpec) DeepCopyInto(out *CloudmuxSpec) {
	*out = *in
	in.ContainerSpec.DeepCopyInto(&out.ContainerSpec)
	if in.Disable != nil {
		in, out := &in.Disable, &out.Disable
		*out = new(bool)
		**out = **in
	}
	if in.Affinity != nil {
		in, out := &in.Affinity, &out.Affinity
		*out = new(v1.Affinity)
		(*in).DeepCopyInto(*out)
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]v1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ImagePullSecrets != nil {
		in, out := &in.ImagePullSecrets, &out.ImagePullSecrets
		*out = make([]v1.LocalObjectReference, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudmuxSpec.
func (in *CloudmuxSpec) DeepCopy() *CloudmuxSpec {
	if in == nil {
		return nil
	}
	out := new(CloudmuxSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerSpec) DeepCopyInto(out *ContainerSpec) {
	*out = *in
	if in.Requests != nil {
		in, out := &in.Requests, &out.Requests
		*out = new(ResourceRequirement)
		(*in).DeepCopyInto(*out)
	}
	if in.Limits != nil {
		in, out := &in.Limits, &out.Limits
		*out = new(ResourceRequirement)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerSpec.
func (in *ContainerSpec) DeepCopy() *ContainerSpec {
	if in == nil {
		return nil
	}
	out := new(ContainerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CronJobSpec) DeepCopyInto(out *CronJobSpec) {
	*out = *in
	in.ContainerSpec.DeepCopyInto(&out.ContainerSpec)
	if in.Affinity != nil {
		in, out := &in.Affinity, &out.Affinity
		*out = new(v1.Affinity)
		(*in).DeepCopyInto(*out)
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]v1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ImagePullSecrets != nil {
		in, out := &in.ImagePullSecrets, &out.ImagePullSecrets
		*out = make([]v1.LocalObjectReference, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CronJobSpec.
func (in *CronJobSpec) DeepCopy() *CronJobSpec {
	if in == nil {
		return nil
	}
	out := new(CronJobSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DBConfig) DeepCopyInto(out *DBConfig) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DBConfig.
func (in *DBConfig) DeepCopy() *DBConfig {
	if in == nil {
		return nil
	}
	out := new(DBConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DaemonSetSpec) DeepCopyInto(out *DaemonSetSpec) {
	*out = *in
	in.ContainerSpec.DeepCopyInto(&out.ContainerSpec)
	if in.Affinity != nil {
		in, out := &in.Affinity, &out.Affinity
		*out = new(v1.Affinity)
		(*in).DeepCopyInto(*out)
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]v1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ImagePullSecrets != nil {
		in, out := &in.ImagePullSecrets, &out.ImagePullSecrets
		*out = make([]v1.LocalObjectReference, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DaemonSetSpec.
func (in *DaemonSetSpec) DeepCopy() *DaemonSetSpec {
	if in == nil {
		return nil
	}
	out := new(DaemonSetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeploymentServicePortSpec) DeepCopyInto(out *DeploymentServicePortSpec) {
	*out = *in
	in.DeploymentSpec.DeepCopyInto(&out.DeploymentSpec)
	out.Service = in.Service
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeploymentServicePortSpec.
func (in *DeploymentServicePortSpec) DeepCopy() *DeploymentServicePortSpec {
	if in == nil {
		return nil
	}
	out := new(DeploymentServicePortSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeploymentServiceSpec) DeepCopyInto(out *DeploymentServiceSpec) {
	*out = *in
	in.DeploymentSpec.DeepCopyInto(&out.DeploymentSpec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeploymentServiceSpec.
func (in *DeploymentServiceSpec) DeepCopy() *DeploymentServiceSpec {
	if in == nil {
		return nil
	}
	out := new(DeploymentServiceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeploymentSpec) DeepCopyInto(out *DeploymentSpec) {
	*out = *in
	in.ContainerSpec.DeepCopyInto(&out.ContainerSpec)
	if in.DNSConfig != nil {
		in, out := &in.DNSConfig, &out.DNSConfig
		*out = new(v1.PodDNSConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Affinity != nil {
		in, out := &in.Affinity, &out.Affinity
		*out = new(v1.Affinity)
		(*in).DeepCopyInto(*out)
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]v1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ImagePullSecrets != nil {
		in, out := &in.ImagePullSecrets, &out.ImagePullSecrets
		*out = make([]v1.LocalObjectReference, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeploymentSpec.
func (in *DeploymentSpec) DeepCopy() *DeploymentSpec {
	if in == nil {
		return nil
	}
	out := new(DeploymentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeploymentStatus) DeepCopyInto(out *DeploymentStatus) {
	*out = *in
	if in.Deployment != nil {
		in, out := &in.Deployment, &out.Deployment
		*out = new(appsv1.DeploymentStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.ImageStatus != nil {
		in, out := &in.ImageStatus, &out.ImageStatus
		*out = new(ImageStatus)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeploymentStatus.
func (in *DeploymentStatus) DeepCopy() *DeploymentStatus {
	if in == nil {
		return nil
	}
	out := new(DeploymentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EChartsSSRSpec) DeepCopyInto(out *EChartsSSRSpec) {
	*out = *in
	in.ContainerSpec.DeepCopyInto(&out.ContainerSpec)
	if in.Disable != nil {
		in, out := &in.Disable, &out.Disable
		*out = new(bool)
		**out = **in
	}
	if in.Affinity != nil {
		in, out := &in.Affinity, &out.Affinity
		*out = new(v1.Affinity)
		(*in).DeepCopyInto(*out)
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]v1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ImagePullSecrets != nil {
		in, out := &in.ImagePullSecrets, &out.ImagePullSecrets
		*out = make([]v1.LocalObjectReference, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EChartsSSRSpec.
func (in *EChartsSSRSpec) DeepCopy() *EChartsSSRSpec {
	if in == nil {
		return nil
	}
	out := new(EChartsSSRSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EctdStatus) DeepCopyInto(out *EctdStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]EtcdClusterCondition, len(*in))
		copy(*out, *in)
	}
	in.Members.DeepCopyInto(&out.Members)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EctdStatus.
func (in *EctdStatus) DeepCopy() *EctdStatus {
	if in == nil {
		return nil
	}
	out := new(EctdStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EsxiAgentConfig) DeepCopyInto(out *EsxiAgentConfig) {
	*out = *in
	out.ServiceCommonOptions = in.ServiceCommonOptions
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EsxiAgentConfig.
func (in *EsxiAgentConfig) DeepCopy() *EsxiAgentConfig {
	if in == nil {
		return nil
	}
	out := new(EsxiAgentConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EsxiAgentStatus) DeepCopyInto(out *EsxiAgentStatus) {
	*out = *in
	in.DeploymentStatus.DeepCopyInto(&out.DeploymentStatus)
	if in.ZoneEsxiAgent != nil {
		in, out := &in.ZoneEsxiAgent, &out.ZoneEsxiAgent
		*out = make(map[string]*DeploymentStatus, len(*in))
		for key, val := range *in {
			var outVal *DeploymentStatus
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = new(DeploymentStatus)
				(*in).DeepCopyInto(*out)
			}
			(*out)[key] = outVal
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EsxiAgentStatus.
func (in *EsxiAgentStatus) DeepCopy() *EsxiAgentStatus {
	if in == nil {
		return nil
	}
	out := new(EsxiAgentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Etcd) DeepCopyInto(out *Etcd) {
	*out = *in
	in.EtcdClusterSpec.DeepCopyInto(&out.EtcdClusterSpec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Etcd.
func (in *Etcd) DeepCopy() *Etcd {
	if in == nil {
		return nil
	}
	out := new(Etcd)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EtcdClusterCondition) DeepCopyInto(out *EtcdClusterCondition) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EtcdClusterCondition.
func (in *EtcdClusterCondition) DeepCopy() *EtcdClusterCondition {
	if in == nil {
		return nil
	}
	out := new(EtcdClusterCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EtcdClusterSpec) DeepCopyInto(out *EtcdClusterSpec) {
	*out = *in
	if in.Pod != nil {
		in, out := &in.Pod, &out.Pod
		*out = new(PodPolicy)
		(*in).DeepCopyInto(*out)
	}
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = new(TLSPolicy)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EtcdClusterSpec.
func (in *EtcdClusterSpec) DeepCopy() *EtcdClusterSpec {
	if in == nil {
		return nil
	}
	out := new(EtcdClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EtcdMembersStatus) DeepCopyInto(out *EtcdMembersStatus) {
	*out = *in
	if in.Ready != nil {
		in, out := &in.Ready, &out.Ready
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Unready != nil {
		in, out := &in.Unready, &out.Unready
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EtcdMembersStatus.
func (in *EtcdMembersStatus) DeepCopy() *EtcdMembersStatus {
	if in == nil {
		return nil
	}
	out := new(EtcdMembersStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GlanceConfig) DeepCopyInto(out *GlanceConfig) {
	*out = *in
	out.ServiceDBCommonOptions = in.ServiceDBCommonOptions
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GlanceConfig.
func (in *GlanceConfig) DeepCopy() *GlanceConfig {
	if in == nil {
		return nil
	}
	out := new(GlanceConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GlanceSpec) DeepCopyInto(out *GlanceSpec) {
	*out = *in
	in.StatefulDeploymentSpec.DeepCopyInto(&out.StatefulDeploymentSpec)
	out.Service = in.Service
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GlanceSpec.
func (in *GlanceSpec) DeepCopy() *GlanceSpec {
	if in == nil {
		return nil
	}
	out := new(GlanceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GlanceStatus) DeepCopyInto(out *GlanceStatus) {
	*out = *in
	in.DeploymentStatus.DeepCopyInto(&out.DeploymentStatus)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GlanceStatus.
func (in *GlanceStatus) DeepCopy() *GlanceStatus {
	if in == nil {
		return nil
	}
	out := new(GlanceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GrafanaConfig) DeepCopyInto(out *GrafanaConfig) {
	*out = *in
	out.DB = in.DB
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GrafanaConfig.
func (in *GrafanaConfig) DeepCopy() *GrafanaConfig {
	if in == nil {
		return nil
	}
	out := new(GrafanaConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostAgentSpec) DeepCopyInto(out *HostAgentSpec) {
	*out = *in
	in.DaemonSetSpec.DeepCopyInto(&out.DaemonSetSpec)
	in.SdnAgent.DeepCopyInto(&out.SdnAgent)
	in.OvnController.DeepCopyInto(&out.OvnController)
	in.HostHealth.DeepCopyInto(&out.HostHealth)
	if in.HostCpuPassthrough != nil {
		in, out := &in.HostCpuPassthrough, &out.HostCpuPassthrough
		*out = new(bool)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostAgentSpec.
func (in *HostAgentSpec) DeepCopy() *HostAgentSpec {
	if in == nil {
		return nil
	}
	out := new(HostAgentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostConfig) DeepCopyInto(out *HostConfig) {
	*out = *in
	out.ServiceCommonOptions = in.ServiceCommonOptions
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostConfig.
func (in *HostConfig) DeepCopy() *HostConfig {
	if in == nil {
		return nil
	}
	out := new(HostConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageStatus) DeepCopyInto(out *ImageStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageStatus.
func (in *ImageStatus) DeepCopy() *ImageStatus {
	if in == nil {
		return nil
	}
	out := new(ImageStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfluxdbSpec) DeepCopyInto(out *InfluxdbSpec) {
	*out = *in
	in.StatefulDeploymentSpec.DeepCopyInto(&out.StatefulDeploymentSpec)
	out.Service = in.Service
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfluxdbSpec.
func (in *InfluxdbSpec) DeepCopy() *InfluxdbSpec {
	if in == nil {
		return nil
	}
	out := new(InfluxdbSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ItsmConfig) DeepCopyInto(out *ItsmConfig) {
	*out = *in
	out.ServiceDBCommonOptions = in.ServiceDBCommonOptions
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ItsmConfig.
func (in *ItsmConfig) DeepCopy() *ItsmConfig {
	if in == nil {
		return nil
	}
	out := new(ItsmConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeystoneConfig) DeepCopyInto(out *KeystoneConfig) {
	*out = *in
	out.ServiceBaseConfig = in.ServiceBaseConfig
	out.DB = in.DB
	out.ClickhouseConf = in.ClickhouseConf
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeystoneConfig.
func (in *KeystoneConfig) DeepCopy() *KeystoneConfig {
	if in == nil {
		return nil
	}
	out := new(KeystoneConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeystoneSpec) DeepCopyInto(out *KeystoneSpec) {
	*out = *in
	in.DeploymentServiceSpec.DeepCopyInto(&out.DeploymentServiceSpec)
	out.PublicService = in.PublicService
	out.AdminService = in.AdminService
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeystoneSpec.
func (in *KeystoneSpec) DeepCopy() *KeystoneSpec {
	if in == nil {
		return nil
	}
	out := new(KeystoneSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeystoneStatus) DeepCopyInto(out *KeystoneStatus) {
	*out = *in
	in.DeploymentStatus.DeepCopyInto(&out.DeploymentStatus)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeystoneStatus.
func (in *KeystoneStatus) DeepCopy() *KeystoneStatus {
	if in == nil {
		return nil
	}
	out := new(KeystoneStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LbagentConfig) DeepCopyInto(out *LbagentConfig) {
	*out = *in
	out.ServiceCommonOptions = in.ServiceCommonOptions
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LbagentConfig.
func (in *LbagentConfig) DeepCopy() *LbagentConfig {
	if in == nil {
		return nil
	}
	out := new(LbagentConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LbagentSpec) DeepCopyInto(out *LbagentSpec) {
	*out = *in
	in.DaemonSetSpec.DeepCopyInto(&out.DaemonSetSpec)
	in.OvnController.DeepCopyInto(&out.OvnController)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LbagentSpec.
func (in *LbagentSpec) DeepCopy() *LbagentSpec {
	if in == nil {
		return nil
	}
	out := new(LbagentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MemberSecret) DeepCopyInto(out *MemberSecret) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MemberSecret.
func (in *MemberSecret) DeepCopy() *MemberSecret {
	if in == nil {
		return nil
	}
	out := new(MemberSecret)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MeterConfig) DeepCopyInto(out *MeterConfig) {
	*out = *in
	out.ServiceDBCommonOptions = in.ServiceDBCommonOptions
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MeterConfig.
func (in *MeterConfig) DeepCopy() *MeterConfig {
	if in == nil {
		return nil
	}
	out := new(MeterConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MeterSpec) DeepCopyInto(out *MeterSpec) {
	*out = *in
	in.StatefulDeploymentSpec.DeepCopyInto(&out.StatefulDeploymentSpec)
	out.Service = in.Service
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MeterSpec.
func (in *MeterSpec) DeepCopy() *MeterSpec {
	if in == nil {
		return nil
	}
	out := new(MeterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MeterStatus) DeepCopyInto(out *MeterStatus) {
	*out = *in
	in.DeploymentStatus.DeepCopyInto(&out.DeploymentStatus)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MeterStatus.
func (in *MeterStatus) DeepCopy() *MeterStatus {
	if in == nil {
		return nil
	}
	out := new(MeterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Minio) DeepCopyInto(out *Minio) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Minio.
func (in *Minio) DeepCopy() *Minio {
	if in == nil {
		return nil
	}
	out := new(Minio)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MonitorStackComponentStatus) DeepCopyInto(out *MonitorStackComponentStatus) {
	*out = *in
	if in.ImageStatus != nil {
		in, out := &in.ImageStatus, &out.ImageStatus
		*out = new(ImageStatus)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MonitorStackComponentStatus.
func (in *MonitorStackComponentStatus) DeepCopy() *MonitorStackComponentStatus {
	if in == nil {
		return nil
	}
	out := new(MonitorStackComponentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MonitorStackGrafanaSpec) DeepCopyInto(out *MonitorStackGrafanaSpec) {
	*out = *in
	out.OAuth = in.OAuth
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MonitorStackGrafanaSpec.
func (in *MonitorStackGrafanaSpec) DeepCopy() *MonitorStackGrafanaSpec {
	if in == nil {
		return nil
	}
	out := new(MonitorStackGrafanaSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MonitorStackGrafanaSpecOAuth) DeepCopyInto(out *MonitorStackGrafanaSpecOAuth) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MonitorStackGrafanaSpecOAuth.
func (in *MonitorStackGrafanaSpecOAuth) DeepCopy() *MonitorStackGrafanaSpecOAuth {
	if in == nil {
		return nil
	}
	out := new(MonitorStackGrafanaSpecOAuth)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MonitorStackGrafanaStatus) DeepCopyInto(out *MonitorStackGrafanaStatus) {
	*out = *in
	in.MonitorStackComponentStatus.DeepCopyInto(&out.MonitorStackComponentStatus)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MonitorStackGrafanaStatus.
func (in *MonitorStackGrafanaStatus) DeepCopy() *MonitorStackGrafanaStatus {
	if in == nil {
		return nil
	}
	out := new(MonitorStackGrafanaStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MonitorStackLokiSpec) DeepCopyInto(out *MonitorStackLokiSpec) {
	*out = *in
	out.ObjectStoreConfig = in.ObjectStoreConfig
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MonitorStackLokiSpec.
func (in *MonitorStackLokiSpec) DeepCopy() *MonitorStackLokiSpec {
	if in == nil {
		return nil
	}
	out := new(MonitorStackLokiSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MonitorStackLokiStatus) DeepCopyInto(out *MonitorStackLokiStatus) {
	*out = *in
	in.MonitorStackComponentStatus.DeepCopyInto(&out.MonitorStackComponentStatus)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MonitorStackLokiStatus.
func (in *MonitorStackLokiStatus) DeepCopy() *MonitorStackLokiStatus {
	if in == nil {
		return nil
	}
	out := new(MonitorStackLokiStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MonitorStackMinioSpec) DeepCopyInto(out *MonitorStackMinioSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MonitorStackMinioSpec.
func (in *MonitorStackMinioSpec) DeepCopy() *MonitorStackMinioSpec {
	if in == nil {
		return nil
	}
	out := new(MonitorStackMinioSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MonitorStackMinioStatus) DeepCopyInto(out *MonitorStackMinioStatus) {
	*out = *in
	in.MonitorStackComponentStatus.DeepCopyInto(&out.MonitorStackComponentStatus)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MonitorStackMinioStatus.
func (in *MonitorStackMinioStatus) DeepCopy() *MonitorStackMinioStatus {
	if in == nil {
		return nil
	}
	out := new(MonitorStackMinioStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MonitorStackPrometheusSpec) DeepCopyInto(out *MonitorStackPrometheusSpec) {
	*out = *in
	if in.Disable != nil {
		in, out := &in.Disable, &out.Disable
		*out = new(bool)
		**out = **in
	}
	out.ThanosSidecarSpec = in.ThanosSidecarSpec
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MonitorStackPrometheusSpec.
func (in *MonitorStackPrometheusSpec) DeepCopy() *MonitorStackPrometheusSpec {
	if in == nil {
		return nil
	}
	out := new(MonitorStackPrometheusSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MonitorStackPrometheusStatus) DeepCopyInto(out *MonitorStackPrometheusStatus) {
	*out = *in
	in.MonitorStackComponentStatus.DeepCopyInto(&out.MonitorStackComponentStatus)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MonitorStackPrometheusStatus.
func (in *MonitorStackPrometheusStatus) DeepCopy() *MonitorStackPrometheusStatus {
	if in == nil {
		return nil
	}
	out := new(MonitorStackPrometheusStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MonitorStackSpec) DeepCopyInto(out *MonitorStackSpec) {
	*out = *in
	out.Minio = in.Minio
	out.Grafana = in.Grafana
	out.Loki = in.Loki
	in.Prometheus.DeepCopyInto(&out.Prometheus)
	out.Thanos = in.Thanos
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MonitorStackSpec.
func (in *MonitorStackSpec) DeepCopy() *MonitorStackSpec {
	if in == nil {
		return nil
	}
	out := new(MonitorStackSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MonitorStackStatus) DeepCopyInto(out *MonitorStackStatus) {
	*out = *in
	in.MinioStatus.DeepCopyInto(&out.MinioStatus)
	in.GrafanaStatus.DeepCopyInto(&out.GrafanaStatus)
	in.LokiStatus.DeepCopyInto(&out.LokiStatus)
	in.PrometheusStatus.DeepCopyInto(&out.PrometheusStatus)
	in.ThanosStatus.DeepCopyInto(&out.ThanosStatus)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MonitorStackStatus.
func (in *MonitorStackStatus) DeepCopy() *MonitorStackStatus {
	if in == nil {
		return nil
	}
	out := new(MonitorStackStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MonitorStackThanosSpec) DeepCopyInto(out *MonitorStackThanosSpec) {
	*out = *in
	out.ObjectStoreConfig = in.ObjectStoreConfig
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MonitorStackThanosSpec.
func (in *MonitorStackThanosSpec) DeepCopy() *MonitorStackThanosSpec {
	if in == nil {
		return nil
	}
	out := new(MonitorStackThanosSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MonitorStackThanosStatus) DeepCopyInto(out *MonitorStackThanosStatus) {
	*out = *in
	in.MonitorStackComponentStatus.DeepCopyInto(&out.MonitorStackComponentStatus)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MonitorStackThanosStatus.
func (in *MonitorStackThanosStatus) DeepCopy() *MonitorStackThanosStatus {
	if in == nil {
		return nil
	}
	out := new(MonitorStackThanosStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Mysql) DeepCopyInto(out *Mysql) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Mysql.
func (in *Mysql) DeepCopy() *Mysql {
	if in == nil {
		return nil
	}
	out := new(Mysql)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NotifySpec) DeepCopyInto(out *NotifySpec) {
	*out = *in
	in.StatefulDeploymentSpec.DeepCopyInto(&out.StatefulDeploymentSpec)
	out.Service = in.Service
	in.Plugins.DeepCopyInto(&out.Plugins)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NotifySpec.
func (in *NotifySpec) DeepCopy() *NotifySpec {
	if in == nil {
		return nil
	}
	out := new(NotifySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObjectStoreConfig) DeepCopyInto(out *ObjectStoreConfig) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObjectStoreConfig.
func (in *ObjectStoreConfig) DeepCopy() *ObjectStoreConfig {
	if in == nil {
		return nil
	}
	out := new(ObjectStoreConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OnecloudCluster) DeepCopyInto(out *OnecloudCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OnecloudCluster.
func (in *OnecloudCluster) DeepCopy() *OnecloudCluster {
	if in == nil {
		return nil
	}
	out := new(OnecloudCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OnecloudCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OnecloudClusterConfig) DeepCopyInto(out *OnecloudClusterConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.Keystone = in.Keystone
	out.RegionServer = in.RegionServer
	out.Glance = in.Glance
	out.Webconsole = in.Webconsole
	out.Logger = in.Logger
	out.Yunionconf = in.Yunionconf
	out.Yunionagent = in.Yunionagent
	out.KubeServer = in.KubeServer
	out.AnsibleServer = in.AnsibleServer
	out.Monitor = in.Monitor
	out.Cloudnet = in.Cloudnet
	out.Cloudproxy = in.Cloudproxy
	out.Cloudevent = in.Cloudevent
	out.APIGateway = in.APIGateway
	out.Cloudmon = in.Cloudmon
	out.Notify = in.Notify
	out.HostAgent = in.HostAgent
	out.Lbagent = in.Lbagent
	out.BaremetalAgent = in.BaremetalAgent
	out.S3gateway = in.S3gateway
	out.Devtool = in.Devtool
	out.Meter = in.Meter
	out.AutoUpdate = in.AutoUpdate
	out.EsxiAgent = in.EsxiAgent
	out.VpcAgent = in.VpcAgent
	out.ServiceOperator = in.ServiceOperator
	out.Itsm = in.Itsm
	out.CloudId = in.CloudId
	out.Report = in.Report
	out.Grafana = in.Grafana
	out.BastionHost = in.BastionHost
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OnecloudClusterConfig.
func (in *OnecloudClusterConfig) DeepCopy() *OnecloudClusterConfig {
	if in == nil {
		return nil
	}
	out := new(OnecloudClusterConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OnecloudClusterConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OnecloudClusterList) DeepCopyInto(out *OnecloudClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OnecloudCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OnecloudClusterList.
func (in *OnecloudClusterList) DeepCopy() *OnecloudClusterList {
	if in == nil {
		return nil
	}
	out := new(OnecloudClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OnecloudClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OnecloudClusterSpec) DeepCopyInto(out *OnecloudClusterSpec) {
	*out = *in
	in.Etcd.DeepCopyInto(&out.Etcd)
	out.Mysql = in.Mysql
	out.Clickhouse = in.Clickhouse
	if in.CertSANs != nil {
		in, out := &in.CertSANs, &out.CertSANs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Services != nil {
		in, out := &in.Services, &out.Services
		*out = make([]Service, len(*in))
		copy(*out, *in)
	}
	out.Minio = in.Minio
	if in.CustomZones != nil {
		in, out := &in.CustomZones, &out.CustomZones
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.Keystone.DeepCopyInto(&out.Keystone)
	in.RegionServer.DeepCopyInto(&out.RegionServer)
	in.RegionDNS.DeepCopyInto(&out.RegionDNS)
	in.Scheduler.DeepCopyInto(&out.Scheduler)
	in.Glance.DeepCopyInto(&out.Glance)
	in.Climc.DeepCopyInto(&out.Climc)
	in.Webconsole.DeepCopyInto(&out.Webconsole)
	in.Logger.DeepCopyInto(&out.Logger)
	in.Yunionconf.DeepCopyInto(&out.Yunionconf)
	in.Yunionagent.DeepCopyInto(&out.Yunionagent)
	in.Influxdb.DeepCopyInto(&out.Influxdb)
	in.VictoriaMetrics.DeepCopyInto(&out.VictoriaMetrics)
	in.Telegraf.DeepCopyInto(&out.Telegraf)
	in.Monitor.DeepCopyInto(&out.Monitor)
	in.APIGateway.DeepCopyInto(&out.APIGateway)
	in.Web.DeepCopyInto(&out.Web)
	in.KubeServer.DeepCopyInto(&out.KubeServer)
	in.AnsibleServer.DeepCopyInto(&out.AnsibleServer)
	in.Cloudnet.DeepCopyInto(&out.Cloudnet)
	in.Cloudproxy.DeepCopyInto(&out.Cloudproxy)
	in.Cloudevent.DeepCopyInto(&out.Cloudevent)
	in.Notify.DeepCopyInto(&out.Notify)
	in.Lbagent.DeepCopyInto(&out.Lbagent)
	in.HostAgent.DeepCopyInto(&out.HostAgent)
	in.HostDeployer.DeepCopyInto(&out.HostDeployer)
	in.HostImage.DeepCopyInto(&out.HostImage)
	in.BaremetalAgent.DeepCopyInto(&out.BaremetalAgent)
	in.S3gateway.DeepCopyInto(&out.S3gateway)
	in.Devtool.DeepCopyInto(&out.Devtool)
	in.Meter.DeepCopyInto(&out.Meter)
	in.AutoUpdate.DeepCopyInto(&out.AutoUpdate)
	in.Cloudmon.DeepCopyInto(&out.Cloudmon)
	in.EsxiAgent.DeepCopyInto(&out.EsxiAgent)
	in.Itsm.DeepCopyInto(&out.Itsm)
	in.ServiceOperator.DeepCopyInto(&out.ServiceOperator)
	in.OvnNorth.DeepCopyInto(&out.OvnNorth)
	in.VpcAgent.DeepCopyInto(&out.VpcAgent)
	in.CloudId.DeepCopyInto(&out.CloudId)
	in.Suggestion.DeepCopyInto(&out.Suggestion)
	in.MonitorStack.DeepCopyInto(&out.MonitorStack)
	in.Scheduledtask.DeepCopyInto(&out.Scheduledtask)
	in.APIMap.DeepCopyInto(&out.APIMap)
	in.Report.DeepCopyInto(&out.Report)
	in.EChartsSSR.DeepCopyInto(&out.EChartsSSR)
	in.BastionHost.DeepCopyInto(&out.BastionHost)
	in.Cloudmux.DeepCopyInto(&out.Cloudmux)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OnecloudClusterSpec.
func (in *OnecloudClusterSpec) DeepCopy() *OnecloudClusterSpec {
	if in == nil {
		return nil
	}
	out := new(OnecloudClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OnecloudClusterStatus) DeepCopyInto(out *OnecloudClusterStatus) {
	*out = *in
	in.Keystone.DeepCopyInto(&out.Keystone)
	in.RegionServer.DeepCopyInto(&out.RegionServer)
	in.Glance.DeepCopyInto(&out.Glance)
	in.Scheduler.DeepCopyInto(&out.Scheduler)
	in.Webconsole.DeepCopyInto(&out.Webconsole)
	in.Influxdb.DeepCopyInto(&out.Influxdb)
	in.VictoriaMetrics.DeepCopyInto(&out.VictoriaMetrics)
	in.Monitor.DeepCopyInto(&out.Monitor)
	in.Logger.DeepCopyInto(&out.Logger)
	in.APIGateway.DeepCopyInto(&out.APIGateway)
	in.Web.DeepCopyInto(&out.Web)
	in.Yunionconf.DeepCopyInto(&out.Yunionconf)
	in.KubeServer.DeepCopyInto(&out.KubeServer)
	in.AnsibleServer.DeepCopyInto(&out.AnsibleServer)
	in.Cloudnet.DeepCopyInto(&out.Cloudnet)
	in.Cloudproxy.DeepCopyInto(&out.Cloudproxy)
	in.Cloudevent.DeepCopyInto(&out.Cloudevent)
	in.Notify.DeepCopyInto(&out.Notify)
	in.BaremetalAgent.DeepCopyInto(&out.BaremetalAgent)
	in.S3gateway.DeepCopyInto(&out.S3gateway)
	in.Devtool.DeepCopyInto(&out.Devtool)
	in.Meter.DeepCopyInto(&out.Meter)
	in.AutoUpdate.DeepCopyInto(&out.AutoUpdate)
	in.EsxiAgent.DeepCopyInto(&out.EsxiAgent)
	in.OvnNorth.DeepCopyInto(&out.OvnNorth)
	in.VpcAgent.DeepCopyInto(&out.VpcAgent)
	in.Etcd.DeepCopyInto(&out.Etcd)
	in.Itsm.DeepCopyInto(&out.Itsm)
	in.CloudId.DeepCopyInto(&out.CloudId)
	in.Cloudmon.DeepCopyInto(&out.Cloudmon)
	in.MonitorStack.DeepCopyInto(&out.MonitorStack)
	in.Scheduledtask.DeepCopyInto(&out.Scheduledtask)
	in.APIMap.DeepCopyInto(&out.APIMap)
	in.Report.DeepCopyInto(&out.Report)
	in.ECharts.DeepCopyInto(&out.ECharts)
	in.BastionHost.DeepCopyInto(&out.BastionHost)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OnecloudClusterStatus.
func (in *OnecloudClusterStatus) DeepCopy() *OnecloudClusterStatus {
	if in == nil {
		return nil
	}
	out := new(OnecloudClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodPolicy) DeepCopyInto(out *PodPolicy) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Affinity != nil {
		in, out := &in.Affinity, &out.Affinity
		*out = new(v1.Affinity)
		(*in).DeepCopyInto(*out)
	}
	in.Resources.DeepCopyInto(&out.Resources)
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]v1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.EtcdEnv != nil {
		in, out := &in.EtcdEnv, &out.EtcdEnv
		*out = make([]v1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PersistentVolumeClaimSpec != nil {
		in, out := &in.PersistentVolumeClaimSpec, &out.PersistentVolumeClaimSpec
		*out = new(v1.PersistentVolumeClaimSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.SecurityContext != nil {
		in, out := &in.SecurityContext, &out.SecurityContext
		*out = new(v1.PodSecurityContext)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodPolicy.
func (in *PodPolicy) DeepCopy() *PodPolicy {
	if in == nil {
		return nil
	}
	out := new(PodPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RegionConfig) DeepCopyInto(out *RegionConfig) {
	*out = *in
	out.ServiceDBCommonOptions = in.ServiceDBCommonOptions
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RegionConfig.
func (in *RegionConfig) DeepCopy() *RegionConfig {
	if in == nil {
		return nil
	}
	out := new(RegionConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RegionDNSProxy) DeepCopyInto(out *RegionDNSProxy) {
	*out = *in
	if in.To != nil {
		in, out := &in.To, &out.To
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RegionDNSProxy.
func (in *RegionDNSProxy) DeepCopy() *RegionDNSProxy {
	if in == nil {
		return nil
	}
	out := new(RegionDNSProxy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RegionDNSSpec) DeepCopyInto(out *RegionDNSSpec) {
	*out = *in
	in.DaemonSetSpec.DeepCopyInto(&out.DaemonSetSpec)
	if in.Proxies != nil {
		in, out := &in.Proxies, &out.Proxies
		*out = make([]RegionDNSProxy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RegionDNSSpec.
func (in *RegionDNSSpec) DeepCopy() *RegionDNSSpec {
	if in == nil {
		return nil
	}
	out := new(RegionDNSSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RegionDNSStatus) DeepCopyInto(out *RegionDNSStatus) {
	*out = *in
	in.DeploymentStatus.DeepCopyInto(&out.DeploymentStatus)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RegionDNSStatus.
func (in *RegionDNSStatus) DeepCopy() *RegionDNSStatus {
	if in == nil {
		return nil
	}
	out := new(RegionDNSStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RegionSpec) DeepCopyInto(out *RegionSpec) {
	*out = *in
	in.DeploymentServicePortSpec.DeepCopyInto(&out.DeploymentServicePortSpec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RegionSpec.
func (in *RegionSpec) DeepCopy() *RegionSpec {
	if in == nil {
		return nil
	}
	out := new(RegionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RegionStatus) DeepCopyInto(out *RegionStatus) {
	*out = *in
	in.DeploymentStatus.DeepCopyInto(&out.DeploymentStatus)
	if in.CustomZones != nil {
		in, out := &in.CustomZones, &out.CustomZones
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RegionStatus.
func (in *RegionStatus) DeepCopy() *RegionStatus {
	if in == nil {
		return nil
	}
	out := new(RegionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceRequirement) DeepCopyInto(out *ResourceRequirement) {
	*out = *in
	if in.CPU != nil {
		in, out := &in.CPU, &out.CPU
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.Memory != nil {
		in, out := &in.Memory, &out.Memory
		x := (*in).DeepCopy()
		*out = &x
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceRequirement.
func (in *ResourceRequirement) DeepCopy() *ResourceRequirement {
	if in == nil {
		return nil
	}
	out := new(ResourceRequirement)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Service) DeepCopyInto(out *Service) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Service.
func (in *Service) DeepCopy() *Service {
	if in == nil {
		return nil
	}
	out := new(Service)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceBaseConfig) DeepCopyInto(out *ServiceBaseConfig) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceBaseConfig.
func (in *ServiceBaseConfig) DeepCopy() *ServiceBaseConfig {
	if in == nil {
		return nil
	}
	out := new(ServiceBaseConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceCommonOptions) DeepCopyInto(out *ServiceCommonOptions) {
	*out = *in
	out.ServiceBaseConfig = in.ServiceBaseConfig
	out.CloudUser = in.CloudUser
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceCommonOptions.
func (in *ServiceCommonOptions) DeepCopy() *ServiceCommonOptions {
	if in == nil {
		return nil
	}
	out := new(ServiceCommonOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceDBCommonOptions) DeepCopyInto(out *ServiceDBCommonOptions) {
	*out = *in
	out.ServiceCommonOptions = in.ServiceCommonOptions
	out.DB = in.DB
	out.ClickhouseConf = in.ClickhouseConf
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceDBCommonOptions.
func (in *ServiceDBCommonOptions) DeepCopy() *ServiceDBCommonOptions {
	if in == nil {
		return nil
	}
	out := new(ServiceDBCommonOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServicePortSpec) DeepCopyInto(out *ServicePortSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServicePortSpec.
func (in *ServicePortSpec) DeepCopy() *ServicePortSpec {
	if in == nil {
		return nil
	}
	out := new(ServicePortSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceSpec) DeepCopyInto(out *ServiceSpec) {
	*out = *in
	out.ServicePortSpec = in.ServicePortSpec
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceSpec.
func (in *ServiceSpec) DeepCopy() *ServiceSpec {
	if in == nil {
		return nil
	}
	out := new(ServiceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StatefulDeploymentSpec) DeepCopyInto(out *StatefulDeploymentSpec) {
	*out = *in
	in.DeploymentSpec.DeepCopyInto(&out.DeploymentSpec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StatefulDeploymentSpec.
func (in *StatefulDeploymentSpec) DeepCopy() *StatefulDeploymentSpec {
	if in == nil {
		return nil
	}
	out := new(StatefulDeploymentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StaticTLS) DeepCopyInto(out *StaticTLS) {
	*out = *in
	if in.Member != nil {
		in, out := &in.Member, &out.Member
		*out = new(MemberSecret)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StaticTLS.
func (in *StaticTLS) DeepCopy() *StaticTLS {
	if in == nil {
		return nil
	}
	out := new(StaticTLS)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TLSPolicy) DeepCopyInto(out *TLSPolicy) {
	*out = *in
	if in.Static != nil {
		in, out := &in.Static, &out.Static
		*out = new(StaticTLS)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TLSPolicy.
func (in *TLSPolicy) DeepCopy() *TLSPolicy {
	if in == nil {
		return nil
	}
	out := new(TLSPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TelegrafSpec) DeepCopyInto(out *TelegrafSpec) {
	*out = *in
	in.DaemonSetSpec.DeepCopyInto(&out.DaemonSetSpec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TelegrafSpec.
func (in *TelegrafSpec) DeepCopy() *TelegrafSpec {
	if in == nil {
		return nil
	}
	out := new(TelegrafSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThanosSidecarSpec) DeepCopyInto(out *ThanosSidecarSpec) {
	*out = *in
	out.ObjectStoreConfig = in.ObjectStoreConfig
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ThanosSidecarSpec.
func (in *ThanosSidecarSpec) DeepCopy() *ThanosSidecarSpec {
	if in == nil {
		return nil
	}
	out := new(ThanosSidecarSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VictoriaMetricsSpec) DeepCopyInto(out *VictoriaMetricsSpec) {
	*out = *in
	in.StatefulDeploymentSpec.DeepCopyInto(&out.StatefulDeploymentSpec)
	out.Service = in.Service
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VictoriaMetricsSpec.
func (in *VictoriaMetricsSpec) DeepCopy() *VictoriaMetricsSpec {
	if in == nil {
		return nil
	}
	out := new(VictoriaMetricsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VpcAgentConfig) DeepCopyInto(out *VpcAgentConfig) {
	*out = *in
	out.ServiceCommonOptions = in.ServiceCommonOptions
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VpcAgentConfig.
func (in *VpcAgentConfig) DeepCopy() *VpcAgentConfig {
	if in == nil {
		return nil
	}
	out := new(VpcAgentConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WebSpec) DeepCopyInto(out *WebSpec) {
	*out = *in
	in.DeploymentSpec.DeepCopyInto(&out.DeploymentSpec)
	in.Overview.DeepCopyInto(&out.Overview)
	in.Docs.DeepCopyInto(&out.Docs)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WebSpec.
func (in *WebSpec) DeepCopy() *WebSpec {
	if in == nil {
		return nil
	}
	out := new(WebSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WebconsoleSpec) DeepCopyInto(out *WebconsoleSpec) {
	*out = *in
	in.DeploymentServicePortSpec.DeepCopyInto(&out.DeploymentServicePortSpec)
	in.Guacd.DeepCopyInto(&out.Guacd)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WebconsoleSpec.
func (in *WebconsoleSpec) DeepCopy() *WebconsoleSpec {
	if in == nil {
		return nil
	}
	out := new(WebconsoleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WebconsoleStatus) DeepCopyInto(out *WebconsoleStatus) {
	*out = *in
	in.DeploymentStatus.DeepCopyInto(&out.DeploymentStatus)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WebconsoleStatus.
func (in *WebconsoleStatus) DeepCopy() *WebconsoleStatus {
	if in == nil {
		return nil
	}
	out := new(WebconsoleStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *YunionagentSpec) DeepCopyInto(out *YunionagentSpec) {
	*out = *in
	in.DaemonSetSpec.DeepCopyInto(&out.DaemonSetSpec)
	out.Service = in.Service
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new YunionagentSpec.
func (in *YunionagentSpec) DeepCopy() *YunionagentSpec {
	if in == nil {
		return nil
	}
	out := new(YunionagentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZoneStatefulDeploymentSpec) DeepCopyInto(out *ZoneStatefulDeploymentSpec) {
	*out = *in
	in.StatefulDeploymentSpec.DeepCopyInto(&out.StatefulDeploymentSpec)
	if in.Zones != nil {
		in, out := &in.Zones, &out.Zones
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZoneStatefulDeploymentSpec.
func (in *ZoneStatefulDeploymentSpec) DeepCopy() *ZoneStatefulDeploymentSpec {
	if in == nil {
		return nil
	}
	out := new(ZoneStatefulDeploymentSpec)
	in.DeepCopyInto(out)
	return out
}
